---
include:
  - project: systemsmystery/ci-includes
    file:
      - yamllint.yml
      - semantic-release.yml
  - template: Terraform-Module.gitlab-ci.yml

stages:
  - validate
  - linting
  - test
  - release
  - deploy

deploy:
  rules:
    - if: $CI_COMMIT_TAG =~ "^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$"