---
include:
  - project: systemsmystery/ci-includes
    file:
      - yamllint.yml
      - semantic-release.yml
  - template: Terraform-Module.gitlab-ci.yml

stages:
  - linting
  - security
  - release
